### ISSUE TITLE
Add command to display the already set token on CLI

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/evalai-cli#123]
The command should be `evalai gettoken`

The output should be the token which is set at `~/.evalai/token.json file`.

**Comment by nileshprasad137** [comment]
I'd like to work on this

**Comment by RishabhJain2018** [comment]
Sure @nileshprasad137 You can work on this.

**Comment by RishabhJain2018** [comment]
@nileshprasad137 Just a heads up, we'll need it urgently in a couple of hours or so :). Thanks for the quick response though.

**Comment by nileshprasad137** [comment]
@RishabhJain2018 should i display the json {"token":"ksjhkja..."} or just the token string "ksjhkja"?

**Comment by RishabhJain2018** [comment]
Thanks a lot for the quick PR. You should display just the token.
