### ISSUE TITLE
Remove red background from all the error messages and make the text red.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/evalai-cli#130]
The current displayed error messages are: (Notice the red background and white font color)
<img width="586" alt="screenshot 2019-02-07 at 10 56 37 pm" src="https://user-images.githubusercontent.com/12206047/52458172-caf2ab00-2b2b-11e9-9c31-92f8345c39ac.png">

Instead, the same text should be displayed as
<img width="552" alt="screenshot 2019-02-07 at 10 57 18 pm" src="https://user-images.githubusercontent.com/12206047/52458187-e9f13d00-2b2b-11e9-9ee0-ddb247cb71b0.png">

**Comment by RishabhJain2018** [comment]
@nileshprasad137 Would you like to fix this too? Meanwhile, I'll review that PR.

**Comment by nileshprasad137** [comment]
Sure , I'll fix this too!

**Comment by RishabhJain2018** [comment]
Thanks!
