### ISSUE TITLE
Make copyright year dynamic

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/evalai-cli#131]
### Observed Behaviour
The copyright year in the footer of docs landing page is outdated - 2018

### Expected Behaviour
Make the copyright year dynamic.

@RishabhJain2018

**Comment by nikhilmudholkar** [comment]
I would like to work on this issue

**Comment by gautamjajoo** [comment]
@nikhilmudholkar Sure! You can work on this issue.

**Comment by nikhilmudholkar** [comment]
@gautamjajooI have submitted the PR. Please review it. Also, the Travis build tests are failing for some reason. All I have done was changing a single line in index.html. How can that lead to the failing of test cases? Can you please help me understand this?

**Comment by prasadgujar** [comment]
@gautamjajoo @nikhilmudholkar did issue is resolved or not? if not let me know I m interested in solving this issue?

**Comment by gautamjajoo** [comment]
@prasadgujar Sure! Go ahead.
