### ISSUE TITLE
Add copy to clipboard feature in command

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/evalai-cli#132]
### Deliverables
- [x] Add support for copying to clipboard for all the commands listed on the docs page. 
- [x] Add an icon for copying the text.
- [x] Show a successful message ` Command copied to clipboard`.

@RishabhJain2018

**Comment by vkartik97** [comment]
@gautamjajoo 
I’d like to take this up

**Comment by RishabhJain2018** [comment]
Sure! you can work on this.
