### ISSUE TITLE
Add a command for logging in to evalai using cli

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/evalai-cli#137]
## Deliverables

- [ ] Add a command `evalai login <username>` which will prompt for the `password`.
- [ ] Once the password is entered, then the command will create a auth_token for the user by using the EvalAI login API, & saves it in the `token.json` file at `~/.evalai/token.json` in the user's system.

**Comment by nileshprasad137** [comment]
I'd like to work on this!

**Comment by RishabhJain2018** [comment]
Sure! @nileshprasad137 You can work on this.

**Comment by nileshprasad137** [comment]
User should not be allowed to see the password while typing, right?

**Comment by RishabhJain2018** [comment]
yeah
