### ISSUE TITLE
Fix bug while copying command

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/evalai-cli#147]
## Bug:

Currently, when the command `evalai set_token <auth_token>` is copied to clipboard, then the content which is copied is `evalai set_token &lt;auth_token&gt;`.

## Expected Behaviour

The copied content should be `evalai set_token <auth_token>`

**Comment by inishchith** [comment]
@RishabhJain2018 can i work on this?

**Comment by gautamjajoo** [comment]
@RishabhJain2018 Also, when the command `evalai push <image:tag> -p 4` is copied , the content is `evalai push &lt;image:tag&gt; -p 4 `.

**Comment by RishabhJain2018** [comment]
Sure @inishchith.
