### ISSUE TITLE
[GCI-2019] Pretty print CLI output on terminal.

### ISSUE THREAD

**Issue by pushkalkatara** [Cloud-CV/evalai-cli#181]
Configure to print output in a pretty format on CLI. Currently, printing output is directly through click python library in plain text. Click supports [ClickUtils](http://click.palletsprojects.com/en/7.x/utils/) with functionalities such as ANSI Color and Pager Support. Student's task - 

1. Modify individual function output using ClickUtils, make a PR and attach a screenshot for the same. Look on commands available [here](https://evalai-cli.cloudcv.org/).
2.  Discuss the idea on how to manage long outputs considering the size of the terminal. (Like in the case of showing all the challenges.)

For queries, contact mentors at https://gitter.im/Cloud-CV/EvalAI

**Comment by m-sameer** [comment]
@pushkalkatara Take a look at my PR

**Comment by RohanSreelesh** [comment]
#197
