### ISSUE TITLE
[docs] Missing instructions for development setup on Windows

### ISSUE THREAD

**Issue by nikochiko** [Cloud-CV/evalai-cli#224]
**Current behavior:**
The `README.md` [Development Setup](https://github.com/Cloud-CV/evalai-cli#development-setup) section only provides instructions for setting up environment on Linux. (The `source` command is specific to Linux)
![cli-dev-setup](https://user-images.githubusercontent.com/37668193/71375285-b56f5e00-25e3-11ea-8c1c-4add14b66cba.PNG)

**Expected behavior:**
The instructions should include steps for Windows as well.

Note: I would like to work on this issue.

**Comment by gautamjajoo** [comment]
PR #110 is already open for the same.

**Comment by nikochiko** [comment]
@gautamjajoo Thanks for informing! :+1:
Closing the issue now.
