### ISSUE TITLE
Code coverage ignores command functions

### ISSUE THREAD

**Issue by matsujika** [Cloud-CV/evalai-cli#262]
**Observed**:
Code coverage doesn't check command functions currently, so even if commands are not tested, code coverage will be 100%.

eg: `push` command in `submissions.py` is not tested, so code coverage of the file must not be 100 % but is 100% (see [here](https://coveralls.io/builds/28046756/source?filename=evalai%2Fsubmissions.py)).

**Comment by nikochiko** [comment]
Can confirm :+1: .
See this coveralls build: https://coveralls.io/jobs/57952941/source_files/1455465142 
I added two functions at the end one of them was a click command: https://coveralls.io/jobs/57952941/source_files/1455465142#L43

I think this is the problem: https://github.com/Cloud-CV/evalai-cli/blob/master/.coveragerc#L9

Nice catch! 👌

**Comment by takitsuse** [comment]
@nikochiko I thought the file was clandestine too but was too busy to check that out (thanks, school exam). I'll give it a try :+1:

**Comment by nikochiko** [comment]
np! 😄
But great job! It would be really easy to miss untested code without a coverage report.
(And even more so with a false one).
