### ISSUE TITLE
Add a progress bar for large submission file uploads

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/evalai-cli#290]
**Description**: 
Currently, the large submission file upload feature shows only a plain text and the user doesn't know of the progress of the file uploaded. We should add a progress bar so that the user knows the progress.

![Screenshot 2020-10-23 at 2 30 55 PM](https://user-images.githubusercontent.com/12206047/97040800-82b43000-153c-11eb-83b6-255b069f353b.png)

**Comment by Ram81** [comment]
Fixed in #291

**Comment by Ram81** [comment]
@RishabhJain2018 we can close this issue
