### ISSUE TITLE
Proposal for creation of challenges through zip using cli.

### ISSUE THREAD

**Issue by savish28** [Cloud-CV/evalai-cli#325]
Creating challenge through zip file by the means of cli.
The API already exists for the same on Evali Backend.
The input requirements are host team and we already have the functionality to create and view teams through cli.

**Comment by savish28** [comment]
@Ram81, Can we have this functionality in the cli, or is it left intentionally?

**Comment by Ram81** [comment]
@savish28 we already support creation of challenge using github. We don't plan to support it using cli.

Closing this issue.
