### ISSUE TITLE
submission error

### ISSUE THREAD

**Issue by kingwmk** [Cloud-CV/evalai-cli#339]
I got an error when submit results.

 $evalai challenge 1719 phase 3392  submit --file ./sub.parquet --large 

Error: {'detail': 'Given token not valid for any token type', 'code': 'token_not_valid', 'messages': [{'token_class': 'RefreshToken', 'token_type': 'refresh', 'message': 'Token is invalid or expired'}]}

**Comment by jeromepatel** [comment]
@kingwmk I am facing a similar error, can you please tell me how did you resolve this? thanks!

**Comment by Ram81** [comment]
Hi @kingwmk @jeromepatel , please update your CLI version to latest one and update the token in your CLI with the latest token from your EvalAI profile to resolve this issue.
