### ISSUE TITLE
Auth Token value gets reset

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/evalai-cli#72]
The token which is placed at `~/.evalai/token.json` gets reset whenever a user runs test cases on his local machine.

**Steps to reproduce:**
1. Add a valid token at `~/.evalai/token.json`.
2. Run the test cases using `py.test`.
3. Check the value of token at `~/.evalai/token.json`

The token `value at step 1 != value at step 3`.

**Comment by isht3** [comment]
#92 Fixes this.
