### ISSUE TITLE
Development templates

### ISSUE THREAD

**Issue by varunagrawal** [Cloud-CV/evalai-cli#8]
We should have templates that describe to new contributors what the expectations of the project are. This requires putting the files in a `.github` folder to allow Github to render them appropriately. Below is a list of files that will be needed to close this issue.

1. [x] - `CONTRIBUTING.md`
2. [x] - `ISSUE_TEMPLATE.md`
3. [x] - `PULL_REQUEST_TEMPLATE.md`

**Comment by RishabhJain2018** [comment]
@varunagrawal I think we should also add the other two remaining templates.

**Comment by RishabhJain2018** [comment]
Closing this since it is already fixed!
