### ISSUE TITLE
Documentation landing page Enhancements

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/evalai-cli#98]
- [x] Please add sample responses with each command.
- [x] Please add options by taking the reference from here and commands can be https://docs.aws.amazon.com/cli/latest/reference/
https://docs.docker.com/engine/reference/commandline/cli/
- [x] Add review comments
- [x] Can `pip install evalai` automatically create `~/.evalai` ?

**Comment by isht3** [comment]
@RishabhJain2018 The last option can definitely be automated. https://stackoverflow.com/questions/15853058/run-custom-task-when-call-pip-install

**Comment by RishabhJain2018** [comment]
@isht3 Can you please implement that?

**Comment by isht3** [comment]
@RishabhJain2018 Yup, I'll reach back today and I'll work on implementing it.

**Comment by RishabhJain2018** [comment]
Closing this since it is already fixed.
